### ISSUE TITLE
[BUG] : Same error page will show after wrong submission.

### ISSUE THREAD

**Issue by abhijivani3001** [UdayGohel/React-Expense-Tracker#1]
## Issue
After adding different wrong issues, same error page is shown.

## Expected solution
For each different wrong submission, error page will show according to that error.

## Screenshots
<img width="60%" src="https://github.com/UdayGohel/React-Expense-Tracker/assets/117305467/16abded7-259f-4b16-af89-6c988b0dd9cd">

**Comment by UdayGohel** [comment]
Thank you for your suggestion.
